// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: proto/order/type/order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddShippingIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId    string `protobuf:"bytes,1,opt,name=order_id,json=product_id,proto3" json:"order_id,omitempty"`
	ShippingId string `protobuf:"bytes,2,opt,name=shipping_id,proto3" json:"shipping_id,omitempty"`
}

func (x *AddShippingIdReq) Reset() {
	*x = AddShippingIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_order_type_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddShippingIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShippingIdReq) ProtoMessage() {}

func (x *AddShippingIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_type_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShippingIdReq.ProtoReflect.Descriptor instead.
func (*AddShippingIdReq) Descriptor() ([]byte, []int) {
	return file_proto_order_type_order_proto_rawDescGZIP(), []int{0}
}

func (x *AddShippingIdReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AddShippingIdReq) GetShippingId() string {
	if x != nil {
		return x.ShippingId
	}
	return ""
}

type UpdateStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=product_id,proto3" json:"order_id,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateStatusReq) Reset() {
	*x = UpdateStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_order_type_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusReq) ProtoMessage() {}

func (x *UpdateStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_type_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateStatusReq) Descriptor() ([]byte, []int) {
	return file_proto_order_type_order_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStatusReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateStatusReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_order_type_order_proto protoreflect.FileDescriptor

var file_proto_order_type_order_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x22, 0x52, 0x0a, 0x10, 0x41, 0x64,
	0x64, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1c,
	0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x22, 0x47,
	0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x77, 0x70, 0x72, 0x7a, 0x2f, 0x70, 0x72, 0x61, 0x73,
	0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_order_type_order_proto_rawDescOnce sync.Once
	file_proto_order_type_order_proto_rawDescData = file_proto_order_type_order_proto_rawDesc
)

func file_proto_order_type_order_proto_rawDescGZIP() []byte {
	file_proto_order_type_order_proto_rawDescOnce.Do(func() {
		file_proto_order_type_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_order_type_order_proto_rawDescData)
	})
	return file_proto_order_type_order_proto_rawDescData
}

var file_proto_order_type_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_order_type_order_proto_goTypes = []any{
	(*AddShippingIdReq)(nil), // 0: order.type.AddShippingIdReq
	(*UpdateStatusReq)(nil),  // 1: order.type.UpdateStatusReq
}
var file_proto_order_type_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_order_type_order_proto_init() }
func file_proto_order_type_order_proto_init() {
	if File_proto_order_type_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_order_type_order_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddShippingIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_order_type_order_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_order_type_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_order_type_order_proto_goTypes,
		DependencyIndexes: file_proto_order_type_order_proto_depIdxs,
		MessageInfos:      file_proto_order_type_order_proto_msgTypes,
	}.Build()
	File_proto_order_type_order_proto = out.File
	file_proto_order_type_order_proto_rawDesc = nil
	file_proto_order_type_order_proto_goTypes = nil
	file_proto_order_type_order_proto_depIdxs = nil
}
